### ISSUE TITLE
bad operand type 

### ISSUE THREAD

**Issue by R3C0Nx00** [ex0dus-0x/D0xk1t#1]
When running start.py, this error occurs 

> Traceback (most recent call last):
  File "start.py", line 439, in <module>
    print  + "NOTE: This version of D0xk1t, v2 is still in the works. Right now, you have obtained an experimental copy." + W
TypeError: bad operand type for unary +: 'str'

**Comment by ex0dus-0x** [comment]
Fixed issue. Accidentally pushed wrong version after fixing README. Derp
