### ISSUE TITLE
requirements.txt issue

### ISSUE THREAD

**Issue by cybgit** [ex0dus-0x/D0xk1t#5]
Is line 19 correct in requirements.txt as it causes an error when i do pip install -r requirements.txt

`Collecting pkg-resources==0.0.0 (from -r requirements.txt (line 19))
  Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 19)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 19))
`

**Comment by ex0dus-0x** [comment]
That is a bug that unfortunately hasn't seen a fix within `pip`. In order to fix this, remove the `pkg-resources==0.0.0` line from the `requirements.txt` file, and run again.
