### ISSUE TITLE
Could not find a version that satisfies the requirement pkg-resources==0.0.0

### ISSUE THREAD

**Issue by maheshtata2020** [ex0dus-0x/D0xk1t#6]
[](url)
<img width="1196" alt="screen shot 2017-09-14 at 2 00 45 pm" src="https://user-images.githubusercontent.com/30227745/30419786-3f779284-9955-11e7-9171-e98c2d5d1923.png">

**Comment by ex0dus-0x** [comment]
Open `requirements.txt` and remove `pkg-resources==0.0.0`.
